/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed gamal
 */
public class ReturnBook extends javax.swing.JFrame {
LibrarianSection l;
    IssueComp [] issue;
   int i=0,count=0;
int j=0,countS=0,countb=0;
boolean flagb,flags,flagi;
FileWriter fw,fw1,fw3;
   Validity v;
   Scanner x;
   Scanner x1;
    Student []student;
    Book1[] book;
    int tempb=0,temps=0,tempi=0;
    public ReturnBook() {
        initComponents();
        this.setLocation(370, 170);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BReturn = new javax.swing.JButton();
        BBack = new javax.swing.JButton();
        TCallNo = new javax.swing.JTextField();
        TStudentID = new javax.swing.JTextField();
        TDay = new javax.swing.JTextField();
        TMonth = new javax.swing.JTextField();
        TYear = new javax.swing.JTextField();
        day = new javax.swing.JLabel();
        Month = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Return Book");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Book Call No:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Student ID:");

        BReturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BReturn.setText("Return Book");
        BReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReturnActionPerformed(evt);
            }
        });

        BBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BBack.setText("Back");
        BBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBackActionPerformed(evt);
            }
        });

        TCallNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCallNoActionPerformed(evt);
            }
        });

        TStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TStudentIDActionPerformed(evt);
            }
        });

        day.setText("day");

        Month.setText("month");

        jLabel6.setText("year");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TCallNo, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(TStudentID)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(TDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(TMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TYear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TCallNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(TStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(Month, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(day, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TDay, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(TMonth)
                    .addComponent(TYear))
                .addGap(17, 17, 17)
                .addComponent(BReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BBack)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TCallNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCallNoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_TCallNoActionPerformed

    private void TStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TStudentIDActionPerformed

    private void BReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReturnActionPerformed
issue=new IssueComp[100];
 try {
        x=new Scanner(new File("C:\\Users\\Ahmed gamal\\Documents\\NetBeansProjects\\Gui\\src\\gui\\IssuedBooks.txt"));
         } catch (FileNotFoundException e) {
        JOptionPane.showMessageDialog(null, " File Error!");
        } 
 i=0;
 while(x.hasNext()){
 
 issue[i]=new IssueComp(x.next(),x.next(),x.next(),x.next(),Integer.parseInt(x.next()),Integer.parseInt(x.next()),Integer.parseInt(x.next()));
 ++i;
 count++;
 }
x.close();
flagi=false;
for(i=0;i<count;++i){
if(issue[i].getCallNo().equals(TCallNo.getText())&&issue[i].getID().equals(TStudentID.getText()))
{  tempi=i;
flagi=true;
break;
}}
    
    try {
        x=new Scanner(new File("C:\\Users\\Ahmed gamal\\Documents\\NetBeansProjects\\Gui\\src\\gui\\Books.txt"));
         } catch (FileNotFoundException e) {
        JOptionPane.showMessageDialog(null, " File Error!");
       
        } 
         flagb=false;
book =new Book1[100];
j=0;
while(x.hasNext()){
      book[j] =new Book1(x.next(),x.next(),x.next(),x.next(),Integer.parseInt(x.next()),Integer.parseInt(x.next()),Integer.parseInt(x.next()),Integer.parseInt(x.next()),Integer.parseInt(x.next()));
         
       
      ++j;
        countb++;}
      x.close();
      j=0;
      for(j=0;j<countb;++j){
      if(TCallNo.getText().equals(book[j].getCallNo())){
      tempb=j;
      flagb=true;
      break;}      }
      
       try {
      x1=new Scanner(new File("C:\\Users\\Ahmed gamal\\Documents\\NetBeansProjects\\Gui\\src\\gui\\Students.txt"));
      } catch (FileNotFoundException e) {
      JOptionPane.showMessageDialog(null, " File Error!");
      }
      j=0;
     student=new Student[100];
      while(x1.hasNext()){
      student[j] =new Student(x1.next(),x1.next(),x1.next(),x1.next(),x1.next(),x1.next(),x1.next(),Integer.parseInt(x1.next()));
      
      
      ++j;
      countS++;}
      for( j=0;j<countS;++j){
      if(student[j].getID().equals(TStudentID.getText()))
      { 
          flags=true;
      temps=j;
      break;}
      } 
      int temp;
      if(flags&&flagb&&flagi){
      temp=(Integer.parseInt(TDay.getText())-issue[i].getDay())+(Integer.parseInt(TMonth.getText())-issue[i].getMonth())*30+(Integer.parseInt(TYear.getText())-issue[i].getYear())*365;
student[temps].setNoOfissued(student[temps].getNoOfissued()-1);
student[temps].decreaseIssueNO();

book[tempb].decreaseIssueNO();

  try{
     
      fw3=new FileWriter( new File("C:\\Users\\Ahmed gamal\\Documents\\NetBeansProjects\\Gui\\src\\gui\\Books.txt"));
       for(i=0;i<countb;++i){
           fw3.write(book[i].getCallNo()+" ");
      fw3.write(book[i].getName()+" ");
      fw3.write(book[i].getAuthor()+" ");
      
      fw3.write(book[i].getPublisher()+" ");
      
      fw3.write(book[i].getQuantity()+" ");
      fw3.write(book[i].getIssuedNo()+" ");
      fw3.write(book[i].getDay()+" ");
      fw3.write(book[i].getMonth()+" ");
      fw3.write(book[i].getYear()+"\n");
      }fw3.close();
      } catch (IOException ex) {
      JOptionPane.showMessageDialog(null, " error opening file");}
   
        
          try { fw =new FileWriter( new File("C:\\Users\\Ahmed gamal\\Documents\\NetBeansProjects\\Gui\\src\\gui\\Students.txt"));
        for(i=0;i<countS;++i){
        
        
         fw.write(student[i].getID()+" ");
         fw.write(student[i].getName()+" ");
        fw.write(student[i].getPassword()+" ");
        fw.write(student[i].getEmail()+" ");
        
        fw.write(student[i].getAddress()+" ");
        fw.write(student[i].getCity()+" ");
        fw.write(student[i].getContactNo()+" ");
        
        fw.write(student[i].getNoOfissued()+"\n");
        } fw.close();} catch (IOException ex) {
        JOptionPane.showMessageDialog(null, " error opening file");}
         
         try { fw1 =new FileWriter( new File("C:\\Users\\Ahmed gamal\\Documents\\NetBeansProjects\\Gui\\src\\gui\\IssuedBooks.txt"));
        for(i=0;i<count;++i){
        if(tempi==i)
            continue;
        
         fw1.write(issue[i].getCallNo()+" ");
         fw1.write(issue[i].getID()+" ");
        fw1.write(issue[i].getName()+" ");
        fw1.write(issue[i].getContactNo()+" ");
        
        fw1.write(issue[i].getDay()+" ");
        fw1.write(issue[i].getMonth()+" ");
        fw1.write(issue[i].getYear()+"\n");
        
       
        } fw1.close();} catch (IOException ex) {
        JOptionPane.showMessageDialog(null, " error opening file");}  
          
if(temp>3){
  JOptionPane.showMessageDialog(null, " File Returned with "+ temp+" days penlty");}
else{
    
    JOptionPane.showMessageDialog(null, " File Returned with") ; 
}      this.setVisible(false);
l=new LibrarianSection();
l.setVisible(true);
     } else{
          JOptionPane.showMessageDialog(null, " callno not founded");
     this.setVisible(false);
l=new LibrarianSection();
l.setVisible(true);
      }


    }//GEN-LAST:event_BReturnActionPerformed

    private void BBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LibrarianSection ls=new LibrarianSection();
       
        ls.setVisible(true);
    }//GEN-LAST:event_BBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBack;
    private javax.swing.JButton BReturn;
    private javax.swing.JLabel Month;
    private javax.swing.JTextField TCallNo;
    private javax.swing.JTextField TDay;
    private javax.swing.JTextField TMonth;
    private javax.swing.JTextField TStudentID;
    private javax.swing.JTextField TYear;
    private javax.swing.JLabel day;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
